### ISSUE TITLE
mkdir -p instead of mkdir

### ISSUE THREAD

**Issue by nreith** [cerebrotech/workspace-configs#24]
Mostly not a problem, but I did have an issue while testing some of these scripts that it fails if the folder already exists. I always use mkdir -p in scripts so it won't throw an error message if it exists and fails.

**Comment by nreith** [comment]
See rstudio/install in particular

**Comment by ChuckRIHead** [comment]
Hey Nick, 

Good suggestion. It's added to a couple of places for our next release.
