### ISSUE TITLE
apt-get update?

### ISSUE THREAD

**Issue by nreith** [cerebrotech/workspace-configs#25]
The rstudio install script failed for me and couldn't find a package because it didn't run apt-get update first, and I forgot to.

It might slow down the scripts if you put apt-get update into each install script.
But it would make them more robust.
Alternatively, maybe a message on the main page that that's essential before running these scripts.

This would apply to any user/admin building a fresh docker image, or anyone who (like me) clears temporary files at the end of each RUN layer, to keep the size down.

**Comment by ChuckRIHead** [comment]
Hey Nick, This is good feedback. We've incorporated it into later recent releases of the rstudio install script.
